apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: backg23
  name: backg23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backg23
  strategy: {}
  template:
    metadata:
      labels:
        app: backg23
    spec:
      containers:
      - image: jeamv/back_so2
        name: back-so2-g23
        resources: {}
      #nodeSelector:
        #kubernetes.io/hostname: gke-cluster-1-default-pool-fca39739-5w3x
status: {}

