apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontg23
  name: frontg23
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontg23
  type: LoadBalancer
status:
  loadBalancer: {}
